services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: offers-sdk-test
    environment:
      - OFFERS_API_REFRESH_TOKEN=${OFFERS_API_REFRESH_TOKEN:-test-token}
      - OFFERS_API_BASE_URL=${OFFERS_API_BASE_URL:-https://python.exercise.applifting.cz}
      - PYTHONPATH=/app/src
    volumes:
      - ./tests:/app/tests:ro
      - ./src:/app/src:ro
    command: poetry run pytest tests/ -v
    profiles:
      - test



  production:
    build:
      context: .
      dockerfile: Dockerfile
    image: offers-sdk-prod
    environment:
      - OFFERS_API_REFRESH_TOKEN=${OFFERS_API_REFRESH_TOKEN}
      - OFFERS_API_BASE_URL=${OFFERS_API_BASE_URL:-https://python.exercise.applifting.cz}
      - PYTHONPATH=/app/src
    command: poetry run python -c "from offers_sdk import OffersClient, OffersAPISettings; print('Production environment ready!')"
    profiles:
      - production

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: offers-sdk-dev
    environment:
      - OFFERS_API_REFRESH_TOKEN=${OFFERS_API_REFRESH_TOKEN:-dev-token}
      - OFFERS_API_BASE_URL=${OFFERS_API_BASE_URL:-https://python.exercise.applifting.cz}
      - PYTHONPATH=/app/src
    volumes:
      - .:/app
      - /app/.venv
    working_dir: /app
    command: poetry run python -c "from offers_sdk import OffersClient, OffersAPISettings; print('Development environment ready!')"
    profiles:
      - dev

  cli:
    build:
      context: .
      dockerfile: Dockerfile
    image: offers-sdk-cli
    environment:
      - OFFERS_API_REFRESH_TOKEN=${OFFERS_API_REFRESH_TOKEN:-cli-token}
      - OFFERS_API_BASE_URL=${OFFERS_API_BASE_URL:-https://python.exercise.applifting.cz}
      - PYTHONPATH=/app/src
    volumes:
      - .:/app
    working_dir: /app
    command: poetry run offers-cli --help
    profiles:
      - cli

  dev-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: offers-sdk-dev-test
    environment:
      - OFFERS_API_REFRESH_TOKEN=${OFFERS_API_REFRESH_TOKEN:-dev-test-token}
      - OFFERS_API_BASE_URL=${OFFERS_API_BASE_URL:-https://python.exercise.applifting.cz}
      - PYTHONPATH=/app/src
    volumes:
      - .:/app
    working_dir: /app
    command: poetry run pytest tests/ -v
    profiles:
      - dev-test

  dev-shell:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: offers-sdk-dev-shell
    environment:
      - OFFERS_API_REFRESH_TOKEN=${OFFERS_API_REFRESH_TOKEN:-dev-shell-token}
      - OFFERS_API_BASE_URL=${OFFERS_API_BASE_URL:-https://python.exercise.applifting.cz}
      - PYTHONPATH=/app/src
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: poetry run python
    profiles:
      - dev-shell